import { join } from "node:path";
import { writeFile } from "fs-extra";

/**
 * Generate a .env file with the provided configuration values
 * Groups related config keys together with comments
 */
export async function generateEnvFile(
	targetDir: string,
	values: Record<string, string>,
): Promise<void> {
	const lines = [
		"# Generated by ClaudeKit CLI setup wizard",
		"# See .env.example for all available options",
		"",
	];

	// Separate Gemini API keys from other values
	const geminiKeys: [string, string][] = [];
	const otherValues: [string, string][] = [];

	for (const [key, value] of Object.entries(values)) {
		if (value) {
			if (key.startsWith("GEMINI_API_KEY")) {
				geminiKeys.push([key, value]);
			} else {
				otherValues.push([key, value]);
			}
		}
	}

	// Add Gemini API keys with rotation comment if multiple
	if (geminiKeys.length > 0) {
		if (geminiKeys.length > 1) {
			lines.push("# Gemini API Keys (rotation enabled)");
			lines.push("# Keys auto-rotate on rate limit (429/RESOURCE_EXHAUSTED)");
		}
		// Sort numerically: GEMINI_API_KEY first, then GEMINI_API_KEY_2, _3, etc.
		geminiKeys.sort((a, b) => {
			const getKeyNumber = (key: string): number => {
				if (key === "GEMINI_API_KEY") return 1;
				const match = key.match(/^GEMINI_API_KEY_(\d+)$/);
				return match ? Number.parseInt(match[1], 10) : 999;
			};
			return getKeyNumber(a[0]) - getKeyNumber(b[0]);
		});
		for (const [key, value] of geminiKeys) {
			lines.push(`${key}=${value}`);
		}
		if (otherValues.length > 0) {
			lines.push(""); // Blank line separator
		}
	}

	// Add other values
	for (const [key, value] of otherValues) {
		lines.push(`${key}=${value}`);
	}

	const envPath = join(targetDir, ".env");
	// Set restrictive permissions (owner read/write only) for security
	await writeFile(envPath, `${lines.join("\n")}\n`, { mode: 0o600 });
}
