/**
 * API key storage in .claude/.env
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ENV_FILE = ".env";
const API_KEY_VAR = "CLAUDEKIT_API_KEY";

/**
 * Get path to .env file in .claude directory
 */
export function getEnvFilePath(claudeDir: string): string {
	return join(claudeDir, ENV_FILE);
}

/**
 * Read existing API key from .env file
 */
export function readExistingApiKey(claudeDir: string): string | null {
	const envPath = getEnvFilePath(claudeDir);

	if (!existsSync(envPath)) {
		return null;
	}

	try {
		const content = readFileSync(envPath, "utf-8");
		const match = content.match(new RegExp(`^${API_KEY_VAR}=(.+)$`, "m"));
		return match?.[1]?.trim() ?? null;
	} catch {
		return null;
	}
}

/**
 * Save API key to .env file
 * Creates file if it doesn't exist, updates if API key already present
 */
export function saveApiKey(claudeDir: string, apiKey: string): void {
	const envPath = getEnvFilePath(claudeDir);
	let content = "";

	if (existsSync(envPath)) {
		content = readFileSync(envPath, "utf-8");

		// Replace existing key or append
		if (content.includes(`${API_KEY_VAR}=`)) {
			content = content.replace(new RegExp(`^${API_KEY_VAR}=.*$`, "m"), `${API_KEY_VAR}=${apiKey}`);
		} else {
			const trimmed = content.trimEnd();
			content = `${trimmed}\n\n# ClaudeKit API Key\n${API_KEY_VAR}=${apiKey}\n`;
		}
	} else {
		content = `# ClaudeKit Environment Variables\n# Generated by ck init\n\n${API_KEY_VAR}=${apiKey}\n`;
	}

	writeFileSync(envPath, content, "utf-8");
}

/**
 * Remove API key from .env file
 */
export function removeApiKey(claudeDir: string): void {
	const envPath = getEnvFilePath(claudeDir);

	if (!existsSync(envPath)) {
		return;
	}

	let content = readFileSync(envPath, "utf-8");
	content = content.replace(new RegExp(`^${API_KEY_VAR}=.*\n?`, "m"), "");
	writeFileSync(envPath, content, "utf-8");
}
