import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { generateEnvFile } from "@/domains/config/config-generator.js";

describe("config-generator", () => {
	let tempDir: string;

	beforeEach(async () => {
		tempDir = join(tmpdir(), `ck-test-${Date.now()}`);
		await mkdir(tempDir, { recursive: true });
	});

	afterEach(async () => {
		await rm(tempDir, { recursive: true, force: true });
	});

	test("should generate .env file with values", async () => {
		const values = {
			GEMINI_API_KEY: "AIzaSyTest123",
			DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/123/abc",
		};

		await generateEnvFile(tempDir, values);

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		expect(content).toContain("GEMINI_API_KEY=AIzaSyTest123");
		expect(content).toContain("DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/123/abc");
	});

	test("should skip empty values", async () => {
		const values = {
			GEMINI_API_KEY: "AIzaSyTest123",
			EMPTY_KEY: "",
		};

		await generateEnvFile(tempDir, values);

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		expect(content).toContain("GEMINI_API_KEY");
		expect(content).not.toContain("EMPTY_KEY");
	});

	test("should include header comments", async () => {
		await generateEnvFile(tempDir, { KEY: "value" });

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		expect(content).toContain("# Generated by ClaudeKit CLI");
	});

	test("should group multiple Gemini API keys with rotation comment", async () => {
		const values = {
			GEMINI_API_KEY: "AIzaSyTest123456789012345678901234567",
			GEMINI_API_KEY_2: "AIzaSyTest456789012345678901234567890",
			GEMINI_API_KEY_3: "AIzaSyTest789012345678901234567890123",
			DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/123/abc",
		};

		await generateEnvFile(tempDir, values);

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		expect(content).toContain("# Gemini API Keys (rotation enabled)");
		expect(content).toContain("# Keys auto-rotate on rate limit");
		expect(content).toContain("GEMINI_API_KEY=AIzaSyTest123456789012345678901234567");
		expect(content).toContain("GEMINI_API_KEY_2=AIzaSyTest456789012345678901234567890");
		expect(content).toContain("GEMINI_API_KEY_3=AIzaSyTest789012345678901234567890123");
	});

	test("should sort Gemini API keys numerically", async () => {
		const values = {
			GEMINI_API_KEY_10: "AIzaSyTest10_678901234567890123456789",
			GEMINI_API_KEY_2: "AIzaSyTest2__678901234567890123456789",
			GEMINI_API_KEY: "AIzaSyTest1__678901234567890123456789",
		};

		await generateEnvFile(tempDir, values);

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		const lines = content.split("\n");
		const keyLine1 = lines.findIndex((l) => l.includes("GEMINI_API_KEY="));
		const keyLine2 = lines.findIndex((l) => l.includes("GEMINI_API_KEY_2="));
		const keyLine10 = lines.findIndex((l) => l.includes("GEMINI_API_KEY_10="));

		expect(keyLine1).toBeLessThan(keyLine2);
		expect(keyLine2).toBeLessThan(keyLine10);
	});

	test("should not add rotation comment for single Gemini key", async () => {
		const values = {
			GEMINI_API_KEY: "AIzaSyTest123456789012345678901234567",
		};

		await generateEnvFile(tempDir, values);

		const content = await readFile(join(tempDir, ".env"), "utf-8");
		expect(content).not.toContain("rotation enabled");
	});
});
